# Generated by Django 6.0.5 on 2026-05-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full descriptive name, e.g. 'Centrifugal Pump P-101'.", max_length=200)),
                ('serial_number', models.CharField(db_index=True, help_text='Manufacturer serial number. Must be globally unique.', max_length=100, unique=True)),
                ('location', models.CharField(help_text="Current physical location, e.g. 'Lagos Depot - Loading Bay 2'.", max_length=200)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', help_text='Physical condition of the equipment.', max_length=10)),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('under_maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], db_index=True, default='in_service', help_text='Current operational status.', max_length=20)),
                ('critical', models.BooleanField(db_index=True, default=False, help_text='Mark True for safety- or production-critical equipment.')),
                ('last_service_date', models.DateField(blank=True, help_text='Date maintenance was last completed.', null=True)),
                ('next_due_date', models.DateField(blank=True, db_index=True, help_text='Next scheduled service date. Used for overdue alerts.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional remarks, fault history, or inspection notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['next_due_date'],
                'indexes': [models.Index(fields=['critical', 'next_due_date'], name='idx_critical_due')],
            },
        ),
    ]
